name: mcmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jax
  - matplotlib
  - numpy
  - numpyro
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - flax
  - ott-jax
  - notebook
  - ipywidgets
  - ipykernel
  - pip:
      - posteriordb